In [4]:
from google.colab import drive
drive.mount('/gdrive')
%cd '/gdrive/My Drive/Colab Notebooks/'

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/My Drive/Colab Notebooks


In [0]:
import os
import numpy as np
import matplotlib.image as mpimg
import pandas as pd
import csv
from PIL import Image

In [0]:
from numpy import genfromtxt
n_barrel_rgb = genfromtxt('data/hw1_class_rest.csv', delimiter=',')

In [8]:
n_barrel_rgb = n_barrel_rgb[1:]
num_nbar_pix = np.shape(n_barrel_rgb)
num_nbar_pix = np.array([num_nbar_pix[0], 0, 0])
print(num_nbar_pix)

[5390813       0       0]


In [9]:
sum_rgb_nbar = np.sum(n_barrel_rgb, axis=0) # get sum of all barrel pixels across all images
mean_rgb_nbar = sum_rgb_nbar / num_nbar_pix[0] # get mean of all barrel pixels across all images
print(sum_rgb_nbar)
print(mean_rgb_nbar)

[6.58759661e+08 6.29953966e+08 5.82523836e+08]
[122.20042895 116.85695015 108.05862418]


In [10]:
mean_rgb_nbar = mean_rgb_nbar.reshape(1, 3)

b = np.ones((num_nbar_pix[0], 1))

b = np.matmul(b, mean_rgb_nbar)

a = n_barrel_rgb - b
aT = np.transpose(a)

cov = np.matmul(aT, a)
cov = cov / num_nbar_pix[0]

print(cov)

[[4560.34098169 4155.15694364 3848.51263196]
 [4155.15694364 4335.58154241 4056.04520827]
 [3848.51263196 4056.04520827 4017.34476096]]


In [11]:
sum_rgb_nbar = sum_rgb_nbar.reshape(1, 3)
mean_rgb_nbar = mean_rgb_nbar.reshape(1, 3)
num_nbar_pix = num_nbar_pix.reshape(1, 3)

print(sum_rgb_nbar)
print(mean_rgb_nbar)

data1 = np.concatenate((sum_rgb_nbar, mean_rgb_nbar, num_nbar_pix), axis=0)
print(data1)

output = np.concatenate((cov, data1), axis=0)

print(output)

[[6.58759661e+08 6.29953966e+08 5.82523836e+08]]
[[122.20042895 116.85695015 108.05862418]]
[[6.58759661e+08 6.29953966e+08 5.82523836e+08]
 [1.22200429e+02 1.16856950e+02 1.08058624e+02]
 [5.39081300e+06 0.00000000e+00 0.00000000e+00]]
[[4.56034098e+03 4.15515694e+03 3.84851263e+03]
 [4.15515694e+03 4.33558154e+03 4.05604521e+03]
 [3.84851263e+03 4.05604521e+03 4.01734476e+03]
 [6.58759661e+08 6.29953966e+08 5.82523836e+08]
 [1.22200429e+02 1.16856950e+02 1.08058624e+02]
 [5.39081300e+06 0.00000000e+00 0.00000000e+00]]


In [0]:
b = open('data/non_barrel_data.csv', 'w')
a = csv.writer(b)
a.writerows(output)
b.close()